services:
    request-certificate-panel:
        container_name: request-certificate-panel
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - request-certificate-panel-network
    # nginx
    request-certificate-panel-nginx:
        container_name: request-certificate-panel-nginx
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8980:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - request-certificate-panel-network
     # db mysql ${DB_DATABASE} //Busca do arquivo .env
    mysql_request:
        container_name: request-certificate-panel-mysql
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - 3307:3306
        networks:
            - request-certificate-panel-network

    request-certificate-panel-phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: request-certificate-panel-phpmyadmin
        links:
            - mysql_request
        restart: always
        environment:
            - PMA_ARBITRARY=1
        ports:
            - 8891:80
        networks:
            - request-certificate-panel-network

networks:
    request-certificate-panel-network:
        driver: bridge
